---return {
---      "romgrk/barbar.nvim",
---      dependencies = { "nvim-tree/nvim-web-devicons" },
---
---
---      init = function() vim.g.barbar_auto_setup = false end,
---
---      config = function()
---            require('barbar').setup {}
---
---            -- THIS IS ALL YOU NEED
---            vim.api.nvim_set_hl(0, 'BufferCurrent',     { fg = '#d8a657', bg = '#1d2021', bold = true })
---            vim.api.nvim_set_hl(0, 'BufferCurrentMod',  { fg = '#ea6962', bg = '#1d2021' })
---            vim.api.nvim_set_hl(0, 'BufferCurrentSign', { fg = '#d8a657', bg = '#1d2021' })
---      end,
---}
