[main]
term=foot
shell=/bin/fish
pad=15x15
font=JetBrainsMono NFP:style=regular:size=15


#[cursor]
#color=d8dee9 d8dee9

[scrollback]
lines=10000

[colors-dark]

# Gruvbox
background=1d2021
foreground=d4be98

regular0=282828
regular1=ea6962
regular2=a9b665
regular3=d8a657
regular4=7daea3
regular5=d3869b
regular6=89b482
regular7=d4be98

bright0=5a534c
bright1=ea6962
bright2=a9b665
bright3=d8a657
bright4=7daea3
bright5=d3869b
bright6=89b482
bright7=ddc7a1

