music_directory     "/home/ebits/Music"
playlist_directory  "/home/ebits/Music/general"
db_file             "/home/ebits/.config/mpd/database"
log_file            "/home/ebits/.config/mpd/log"
pid_file            "/home/ebits/.config/mpd/pid"
state_file          "/home/ebits/.config/mpd/state"
sticker_file        "/home/ebits/.config/mpd/sticker.sql"

audio_output {
        type            "pulse"
        name            "My PulseAudio Output"
}

audio_output {
        type            "fifo"
        name            "my_fifo"
        path            "/tmp/mpd.fifo"
        format          "44100:16:2"
}

bind_to_address    "127.0.0.1:6600"
