font_size: 22
theme: gruvbox
tree_1:
  general:
    github: "https://www.github.com/"
    gmail: "https://mail.google.com/"
    whatsapp: "https://web.whatsapp.com/"
    reddit: "https://reddit.com/"
    unixporn: "https://www.reddit.com/r/unixporn/"
    youtube: "https://youtube.com/"
  College:
    vtop: "https://vtopcc.vit.ac.in/"
    nptel: "https://onlinecourses.nptel.ac.in/"
    iamneo: "https://vitcolab945.examly.io"
    vitol: "https://vitolcc.vit.ac.in/"
    lms: "https://lms.vit.ac.in/"
tree_2:
  news:
    hackernews: "https://news.ycombinator.com/"
    itsFOSS: "https://news.itsfoss.com/"
  dev:
    ARM_docs: "https://mariokartwii.com/armv8/ch2.html"
    GPU_glossary: "https://modal.com/gpu-glossary"
    Networks: "http://www.tcpipguide.com/free/t_toc.htm"
