" Enable relative line numbers
set relativenumber

" Enable auto indentation with tabs
set expandtab       " Use spaces instead of tabs
set tabstop=4       " Set tab width to 4 spaces
set shiftwidth=4    " Indentation width
set softtabstop=4   " Spaces per tab
set smartindent     " Auto indent for new lines
set autoindent      " Automatically indent new lines

" Enable line numbering
set number

" Install Nord theme and auto-pairs plugin (using vim-plug)
call plug#begin('~/.vim/plugged')

" Nord theme plugin
Plug 'arcticicestudio/nord-vim'

" Auto-pairs plugin for automatic bracket/parenthesis/brace closing
Plug 'jiangmiao/auto-pairs'

" Snippet plugin
Plug 'honza/vim-snippets'

" Completion plugin (YouCompleteMe or coc.nvim)
" Option 1: YouCompleteMe
Plug 'ycm-core/YouCompleteMe'

" Option 2: coc.nvim
" Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

" Apply the Nord color scheme
colorscheme nord

" Enable autocompletion
" For YouCompleteMe
" let g:ycm_auto_enable = 1

" For coc.nvim
" autocmd BufRead,BufNewFile * call coc#config('suggest.autoTrigger', 'always')
" autocmd BufRead,BufNewFile * call coc#config('suggest.enablePreview', v:false)

" Enable snippet support
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsListSnippets="<c-x><c-o>"

